# Generated by Django 6.0.5 on 2026-05-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_tecnologia_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autores",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=500),
        ),
    ]
