# Generated by Django 6.0.5 on 2026-05-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_alter_tfc_autores_alter_tfc_orientador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="autores",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.TextField(),
        ),
    ]
