# Generated by Django 6.0.5 on 2026-05-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0014_alter_tfc_autores_alter_tfc_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.TextField(blank=True, null=True),
        ),
    ]
