# Generated by Django 6.0.5 on 2026-05-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0015_alter_tfc_orientador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="makingof",
            name="fotografia_caderno",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="makingof/"
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(max_length=255, upload_to="projetos/"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(max_length=255, upload_to="tecnologias/"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(max_length=255, upload_to="ucs/"),
        ),
    ]
