# Generated by Django 6.0.5 on 2026-05-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artigo",
            name="fotografia",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="artigos/"
            ),
        ),
    ]
